---
- name: Conectar a servidor EC2 y realizar tareas de Jenkins
  hosts: "all"
  gather_facts: yes
  become: yes

  tasks:
    - name: Imprimir Hola Mundo
      command: echo "Hola Mundo"

  tasks:
    - name: Actualizar paquetes
      package:
        name:
          #- python3
          #- python3-pip
          #- nodejs
          #- npm
          #- java-11-openjdk
          #- ruby
        state: latest
      command: echo "termino de instalar"