---
- name: Conectar a servidor EC2 y realizar tareas de Jenkins
  hosts: "44.215.121.231"
  gather_facts: yes

  tasks:
    - name: Instalar el cliente de Jenkins
      apt:
        name: jenkins-cli
        update_cache: yes
      become: yes

    - name: Descargar la línea de comandos de Jenkins
      shell: |
        wget http://localhost:8080/jnlpJars/jenkins-cli.jar
        chmod +x jenkins-cli.jar
      args:
        executable: /bin/bash
      become: yes
      become_user: admin  

    - name: Crear un job de ejemplo en Jenkins
      shell: |
        java -jar jenkins-cli.jar -s http://localhost:8080/ create-job MiPrimerJob < config.xml
      args:
        executable: /bin/bash
      become: yes
      become_user: admin  
